name: vulnerable-action
description: 'A fake malicious action to test harden runner with'

inputs:
  github-token:
    required: true

runs:
  using: composite
  steps:
    - name: Install GitHub CLI
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y gh

    - name: Authenticate GitHub CLI
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        echo "${{ inputs.github-token }}" | gh auth login --with-token

    - name: List repository secrets
      shell: bash
      run: |
        gh secret list --repo $GITHUB_REPOSITORY