# .github/workflows/docker-build.yml

name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: chronograph-pe/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f
      with:
        egress-policy: audit
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build Image
      run: |
        docker build -t python-docker-app .

    - name: Run Image
      run: |
        docker run -p 5000:5000 python-docker-app
