name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f
      with:
        egress-policy: audit

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Send Stuff
      id: send-stuff
      continue-on-error: true
      uses: ./.github/actions/send-stuff
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build Image
      run: |
        docker build -t python-docker-app .

    - name: Run Image
      run: |
        docker run -p 5000:5000 python-docker-app
